#!/bin/bash
# download broadcast ephemeris files
# need to provide year and day of year
# for example, download_ephemeris 2025 186

YYYY=$1
DDD=$2

YY=${YYYY:2:4}

curl -O -L "https://geodesy.noaa.gov/corsdata/rinex/"$YYYY"/"$DDD"/brdc"$DDD"0."$YY"n.gz"
gunzip "brdc"$DDD"0."$YY"n.gz"


